### ISSUE TITLE
Is there a way to get Uncommon/Rare colored labels for each set? And possible to get the Mana symbols (Mono, dual, Tri, etc)?

### ISSUE THREAD

**Issue by LordZeal** [davidfischer/mtg-printable-set-label-generator#15]
I love these labels so thank you! Is there a way to adjust the font color when printing to get the Silver and Gold colors for Uncommon/Rare versions? 

Also, is there a way to add in the Mana symbols? I can't find those anywhere in a similar printable format. A row of the single symbols and the maybe rows for the dual, tri, quad and 5 color combos?

**Comment by davidfischer** [comment]
You could certainly adjust the colors by changing the SVG files that are part of the zip output. Use a program like Inkscape to modify SVGs.

As to mana symbols, that seems outside the scope of the sets but I do have a tip. For high quality symbols, use a font like [this one](http://alexandrearpin.com/mtg-font/index.html)

**Comment by LordZeal** [comment]
Cool, thanks!
