### ISSUE TITLE
Webpage generator indentation

### ISSUE THREAD

**Issue by Bradw-17** [davidfischer/mtg-printable-set-label-generator#18]
I just generated some sheets using the webpage and noticed that certain sets with long names ran over the set symbol, such as Baldur's Gate: 
![example](https://user-images.githubusercontent.com/31972543/210810308-4edcd3c8-33a5-426d-90b7-6d3c5925cdf7.PNG)

**Comment by davidfischer** [comment]
Ya, Wizards keeps printing these super long set names. Currently, I've manually shortened the names to fit. If names like `Phyrexia: All Will Be One Commander` keep coming out, I'm going to have to rethink that.

In the short term, I shortened the recent ones and it should be live on the site in the next 10 minutes.
