### ISSUE TITLE
Webpage front end throwing a Server Error(500)

### ISSUE THREAD

**Issue by JonGalasso** [davidfischer/mtg-printable-set-label-generator#19]
Not sure if I'm just using it wrong but I can't get it to run

**Comment by JonGalasso** [comment]
This is after hitting the generate button

**Comment by davidfischer** [comment]
I'll take a closer look this evening. It seems to be related to a specific set (or a large number of sets) since it works on a smaller number of sets.

**Comment by JonGalasso** [comment]
I found it, "starter commander decks" causes it to throw the error. The logo for it doesn't load properly either. I even tested it by enabling everything except it so it's not about the number of sets.
