### ISSUE TITLE
pdf conversion

### ISSUE THREAD

**Issue by MexicanoRS** [davidfischer/mtg-printable-set-label-generator#2]
you could add conversion to pdf instead of SVG and add other paper formats.
We use A4 paper a lot in Brazil. Sorry for the weird implementation. it's my first time messing with pyton and suggesting something on github. Congratulations on the program, it worked on linux on windows!
```
[...]
import cairosvg 

[...]

COLS = 4
ROWS = 15
WIDTH = 2970  # Width in 1/10 mm of US Letter paper
HEIGHT = 2100
MARGIN = 200

[...]

if __name__ == "__main__":
    page = 1
    labels = create_set_label_data()
    while labels:
        exps = []
        while labels and len(exps) < (ROWS * COLS):
            exps.append(labels.pop(0))

        # Render the label template
        template = ENV.get_template("labels.svg")
        output = template.render(
            labels=exps,
            horizontal_guides=create_horizontal_cutting_guides(),
            vertical_guides=create_vertical_cutting_guides(),
            WIDTH=WIDTH,
            HEIGHT=HEIGHT,
        )
        outfile = os.path.join(BASE_DIR, "output", f"labels{page:02}_A4.svg")
        print(f"Writing {outfile}...")
        with open(outfile, "w") as fd:
            fd.write(output)
            cairosvg.svg2pdf(
                file_obj=open(os.path.join(BASE_DIR, "output", f"labels{page:02}_A4.svg"), "rb"),  write_to= os.path.join(BASE_DIR, "output", f"labels{page:02}_A4.pdf"))

        page += 1
        
        
        
        # US_Letter
COLS = 4
ROWS = 15
WIDTH = 2790  # Width in 1/10 mm of US Letter paper
HEIGHT = 2160
MARGIN = 200
START_X = MARGIN
START_Y = MARGIN
DELTA_X = (WIDTH - (2 * MARGIN)) / COLS
DELTA_Y = (HEIGHT - (2 * MARGIN)) / ROWS

if __name__ == "__main__":
    page = 1
    labels = create_set_label_data()
    while labels:
        exps = []
        while labels and len(exps) < (ROWS * COLS):
            exps.append(labels.pop(0))

        # Render the label template
        template = ENV.get_template("labels.svg")
        output = template.render(
            labels=exps,
            horizontal_guides=create_horizontal_cutting_guides(),
            vertical_guides=create_vertical_cutting_guides(),
            WIDTH=WIDTH,
            HEIGHT=HEIGHT,
        )
        outfile = os.path.join(BASE_DIR, "output", f"labels{page:02}_Letter_US.svg")
        print(f"Writing {outfile}...")
        with open(outfile, "w") as fd:
            fd.write(output)
            cairosvg.svg2pdf(
                file_obj=open(os.path.join(BASE_DIR, "output", f"labels{page:02}_Letter_US.svg"), "rb"),  write_to= os.path.join(BASE_DIR, "output", f"labels{page:02}_Letter_US.pdf"))

        page += 1
```
AH! I added some abbreviations but they are still not legal. I don't know the best way to summarize some edition names.

```
RENAME_SETS = {
 [...]
    "Mystery Booster Retail Edition Foils": "Mystery Booster Retail Edition",
    "Mystery Booster Playtest Cards 2021": "Mystery Booster Playtest 2021",
    "Adventures in the Forgotten Realms": "Advnt. in the Forgotten Realms"
}
```
[label-generator.zip](https://github.com/davidfischer/mtg-printable-set-label-generator/files/7873037/label-generator.zip)
[labels04_Letter_US.pdf](https://github.com/davidfischer/mtg-printable-set-label-generator/files/7873039/labels04_Letter_US.pdf)
[labels01_A4.pdf](https://github.com/davidfischer/mtg-printable-set-label-generator/files/7873040/labels01_A4.pdf)
[labels01_Letter_US.pdf](https://github.com/davidfischer/mtg-printable-set-label-generator/files/7873041/labels01_Letter_US.pdf)
[labels02_A4.pdf](https://github.com/davidfischer/mtg-printable-set-label-generator/files/7873042/labels02_A4.pdf)
[labels02_Letter_US.pdf](https://github.com/davidfischer/mtg-printable-set-label-generator/files/7873043/labels02_Letter_US.pdf)
[labels03_A4.pdf](https://github.com/davidfischer/mtg-printable-set-label-generator/files/7873044/labels03_A4.pdf)
[labels03_Letter_US.pdf](https://github.com/davidfischer/mtg-printable-set-label-generator/files/7873045/labels03_Letter_US.pdf)
[labels04_A4.pdf](https://github.com/davidfischer/mtg-printable-set-label-generator/files/7873046/labels04_A4.pdf)

**Comment by davidfischer** [comment]
I'm glad you got use out of the program. I'll take your suggestions and see if I can package up a version over the weekend. It should be easy enough to add a command line option to use A4 paper.
