### ISSUE TITLE
Titles running into symbol

### ISSUE THREAD

**Issue by jtdbod** [davidfischer/mtg-printable-set-label-generator#21]
The titles are running into the Symbols for MoM:Commander, MoM:Aftermath and Tales of Middle Earth Commander

**Comment by StepKie** [comment]
Would be fixed by #23 .

**Comment by davidfischer** [comment]
This is fixed by #23. Whenever there's a super long set name, we manually create a shortened name for it.

**Comment by davidfischer** [comment]
Thanks to @Hottemax for the fix.
